### ISSUE TITLE
Missing DJANGO_SETTINGS_MODULE

### ISSUE THREAD

**Issue by jonashaag** [nedbat/django_coverage_plugin#18] opened 2016-02-02 00:42 UTC
With empty `.coveragerc`:

```
$ coverage run foo/manage.py test bar
[...works...]
```

With django-coverage-plugin in `.coveragerc`:

```
[run]
plugins =
  django_coverage_plugin
```

```
$ coverage run foo/manage.py test bar
[...]
django.core.exceptions.ImproperlyConfigured: Requested setting TEMPLATES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

`manage.py` is unmodified (generated by Django).

**Comment by nedbat** [comment] 2016-02-02 00:47
Can you show the complete error report with traceback?

**Comment by jonashaag** [comment] 2016-02-02 01:12
Sure. Actually from the traceback it looks more like django-coverage-plugin wants the use settings before `manage.py` has loaded the environment variable; changing the title accordingly.

```pytb
Traceback (most recent call last):
  File "/my/project/.tox/py35-django18/bin/coverage", line 11, in <module>
    sys.exit(main())
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/coverage/cmdline.py", line 741, in main
    status = CoverageScript().command_line(argv)
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/coverage/cmdline.py", line 481, in command_line
    return self.do_run(options, args)
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/coverage/cmdline.py", line 610, in do_run
    self.coverage.erase()
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/coverage/control.py", line 709, in erase
    self._init()
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/coverage/control.py", line 218, in _init
    self.plugins = Plugins.load_plugins(self.config.plugins, self.config, self.debug)
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/coverage/plugin_support.py", line 49, in load_plugins
    coverage_init(plugins, options)
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/django_coverage_plugin/__init__.py", line 11, in coverage_init
    reg.add_file_tracer(DjangoTemplatePlugin())
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/django_coverage_plugin/plugin.py", line 122, in __init__
    check_debug()
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/django_coverage_plugin/plugin.py", line 52, in check_debug
    templates = getattr(settings, 'TEMPLATES', [])
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/my/project/.tox/py35-django18/lib/python3.5/site-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting TEMPLATES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by jonashaag** [comment] 2016-02-02 01:14
Note that this worked in 1.1 and broke in 1.2, I can bisect the commit for you if you want

**Comment by nedbat** [comment] 2016-04-03 14:48
@jonashaag more details about how reproduce this, or which commit it was, would be great.

**Comment by jonashaag** [comment] 2016-04-03 18:05
Just use `startproject`, `startapp`, and then the settings I show above.

**Comment by jonashaag** [comment] 2016-04-15 09:03
Bump

**Comment by keimlink** [comment] 2016-05-18 07:35
@jonashaag Did you manage to identify the exact commit that causes the error?

**Comment by jonashaag** [comment] 2016-05-18 07:43
@keimlink Yes but I don't remember which one it was, you can simply run `git bisect` to find it

**Comment by rfleschenberg** [comment] 2016-05-18 20:07
bisect points at 0085fb83807b58863789d4fe3f92718322751b0a

**Comment by nedbat** [comment] 2016-05-18 20:37
I'll be able to jump into this more easily with a zipfile or specific instructions about how to reproduce it.

**Comment by rfleschenberg** [comment] 2016-05-18 21:24
Steps to reproduce:
```
mkvirtualenv issue-18
pip install git+https://github.com/nedbat/django_coverage_plugin.git
django-admin startproject myprj
printf "[run]\nplugins = \n  django_coverage_plugin\n" > .coveragerc
coverage run myprj/manage.py test
```

**Comment by rfleschenberg** [comment] 2016-05-18 21:28
Actually, it works fine if you run from the directory where manage.py is located. I think that is expected. You should always run ``manage.py`` from its direct parent directory. Otherwise,  ``DJANGO_SETTINGS_MODULE`` will point at the wrong target (unless you take some other measure to get your project into ``sys.path``).

@jonashaag: does it work if you cd into ``foo`` and run ``./manage.py test``?

**Comment by rfleschenberg** [comment] 2016-05-18 22:04
Eh, sorry. My comment above about having to run ``manage.py`` from its parent dir is wrong. ``DJANGO_SETTINGS_MODULE`` is relative to the location of ``manage.py``. I really shouldn't debug things at this time of the day :-/

But at least I found out that the current directory has something to do with it. Happy debugging ;)

**Comment by nedbat** [comment] 2016-05-23 01:12
The working directory is a red herring: that's because there's no .coveragerc in the subdirectory. If you copy it there, the failure happens in either directory.

I think the fix is to move the plugin's access of settings to later, when it is actually needed.

**Comment by emmalemma** [comment] 2016-05-24 02:10
Just chiming in to say I fixed this same bug when using `pytest-cov` by just commenting out `check_debug()`:  https://github.com/emmalemma/django_coverage_plugin/commit/e083da1624831c9485ec44f569d0689a59249f36 True, I won't get the nice warning if the settings are wrong, just 0% coverage; on the upside, when the settings are correct, the plugin actually works.

If anyone's trying to find a better solution, I can tell you that you need to find a way to raise this error after `__init__`, since in this configuration that happens before settings have been loaded. Unfortunately `coverage` seems to like to swallow all errors after that point. Good luck.

**Comment by nedbat** [comment] 2016-06-02 16:07
This is fixed as of commit fdb0892966362e2ded39e4124d095a999a28543e

**Closed by nedbat** 2016-06-02 16:07 UTC

**Comment by nedbat** [comment] 2016-06-02 16:32
I'll make a new release.  If you could test it out, that would be great.

**Comment by emmalemma** [comment] 2016-06-02 19:32
Thanks! With my config, fdb0892 works but still doesn't log the error when template debugging is off. Nothing in the coverage debug log either. For the record I'm using:

```
coverage (4.1)
pytest (2.9.1)
pytest-cov (2.2.1)
pytest-django (2.9.1)
```

I'm not sure which of these is responsible for eating the exception.

**Comment by nedbat** [comment] 2016-06-03 20:48
@emmalemma Can you show me some output?  When I run a project without a debug setting, I get this:
```
$ coverage run manage.py test
Coverage.py warning: Disabling plugin 'django_coverage_plugin.DjangoTemplatePlugin' due to an exception:
Traceback (most recent call last):
  File "/usr/local/virtualenvs/django_coverage/lib/python2.7/site-packages/coverage/control.py", line 499, in _should_trace_internal
    file_tracer = plugin.file_tracer(canonical)
  File "/Users/ned/coverage/django_coverage_plugin/django_coverage_plugin/plugin.py", line 154, in file_tracer
    check_debug()
  File "/Users/ned/coverage/django_coverage_plugin/django_coverage_plugin/plugin.py", line 69, in check_debug
    "Template debugging must be enabled in settings."
DjangoTemplatePluginException: Template debugging must be enabled in settings.
Creating test database for alias 'default'...
..........
----------------------------------------------------------------------
Ran 10 tests in 0.060s

OK
Destroying test database for alias 'default'...
$
```

**Comment by emmalemma** [comment] 2016-06-03 22:17
Sure. I can reproduce this with a minimal pytest setup:

```
virtualenv -p python3 venv
source venv/bin/activate
pip install django pytest pytest-django pytest-cov
pip install -e "git+https://github.com/nedbat/django_coverage_plugin@fdb0892966362e2ded39e4124d095a999a28543e#egg=django_coverage_plugin"

django-admin startproject coverage_test
cd coverage_test
echo "[run]\nplugins=django_coverage_plugin" > .coveragerc

mkdir coverage_test/templates
echo "test" > coverage_test/templates/test.html
```

create `tests.py`:
```
from django.template.loader import render_to_string

def test():
	render_to_string('test.html')
```

edit settings.py:
```
INSTALLED_APPS.append('coverage_test')
TEMPLATES[0]['OPTIONS']['debug'] = True
```

Demonstrate it works:

```
> export DJANGO_SETTINGS_MODULE=coverage_test.settings
> py.test tests.py --cov coverage_test

====================================== test session starts =======================================
platform darwin -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
django settings: coverage_test.settings (from environment variable)
rootdir: /Users/emma/Dropbox/Projects/coverage_test/coverage_test, inifile: 
plugins: cov-2.2.1, django-2.9.1
collected 1 items 

tests.py .
------------------------ coverage: platform darwin, python 3.5.1-final-0 -------------------------
Name                                Stmts   Miss  Cover
-------------------------------------------------------
coverage_test/__init__.py               0      0   100%
coverage_test/settings.py              20      0   100%
coverage_test/templates/test.html       1      0   100%
coverage_test/urls.py                   3      3     0%
coverage_test/wsgi.py                   4      4     0%
-------------------------------------------------------
TOTAL                                  28      7    75%

==================================== 1 passed in 0.32 seconds ====================================
```

Then set `TEMPLATES[0]['OPTIONS']['debug'] = False`, and demonstrate it fails silently:

```
> py.test tests.py --cov coverage_test

====================================== test session starts =======================================
platform darwin -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
django settings: coverage_test.settings (from environment variable)
rootdir: /Users/emma/Dropbox/Projects/coverage_test/coverage_test, inifile: 
plugins: cov-2.2.1, django-2.9.1
collected 1 items 

tests.py .
------------------------ coverage: platform darwin, python 3.5.1-final-0 -------------------------
Name                        Stmts   Miss  Cover
-----------------------------------------------
coverage_test/__init__.py       0      0   100%
coverage_test/settings.py      20      0   100%
coverage_test/urls.py           3      3     0%
coverage_test/wsgi.py           4      4     0%
-----------------------------------------------
TOTAL                          27      7    74%

==================================== 1 passed in 0.27 seconds ====================================
```

If I run the same thing on emmalemma@e083da1, with `check_debug` disabled, it shows 0% coverage:

```
> py.test tests.py --cov coverage_test

====================================== test session starts =======================================
platform darwin -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
django settings: coverage_test.settings (from environment variable)
rootdir: /Users/emma/Dropbox/Projects/coverage_test/coverage_test, inifile: 
plugins: cov-2.2.1, django-2.9.1
collected 1 items 

tests.py .
------------------------ coverage: platform darwin, python 3.5.1-final-0 -------------------------
Name                                Stmts   Miss  Cover
-------------------------------------------------------
coverage_test/__init__.py               0      0   100%
coverage_test/settings.py              20      0   100%
coverage_test/templates/test.html       1      0   100%
coverage_test/urls.py                   3      3     0%
coverage_test/wsgi.py                   4      4     0%
-------------------------------------------------------
TOTAL                                  28      7    75%

==================================== 1 passed in 0.23 seconds ====================================
```

Presumably, the check in fdb0892 is working properly, and killing the plugin; it's just not getting to stderr or stopping pytest.

The original issue is probably fixed by this patch. There might not be anything for the plugin to do about my problem, since it's probably something in pytest or pytest-cov. Or there might a configuration somewhere. I haven't spent much time hunting since the actual plugin is working just fine for me.

**Comment by nedbat** [comment] 2016-06-04 20:45
@emmalemma thanks for the detailed steps! I'm looking into what is hiding the exception.  BTW: `echo "[run]\nplugins=django_coverage_plugin" > .coveragerc` put a backslash-n into the rc file, but once I fixed that, the reproduction was easy. :)

**Comment by emmalemma** [comment] 2016-06-05 16:53
Hah, whoops! I only use zsh, forgot that would happen in bash. I guess I need to use `printf` instead :)

Thanks for taking the time to look into this, and especially thanks for your work on the plugin in the first place.

**Comment by nedbat** [comment] 2016-06-12 15:21
I opened #25 to deal with the invisible exception.

**Comment by GabLeRoux** [comment] 2018-10-16 19:35
I was getting the following error:

> django_coverage_plugin.plugin.DjangoTemplatePluginException: Template debugging must be enabled in settings.

I thought I had the setting enabled, but here's the thing:

> The TEMPLATE_DEBUG setting is deprecated in Django 1.8. The new way to do it is described here: stackoverflow.com/a/32446043/2319697

```python
DEBUG = True

TEMPLATES = [
    {
        ...
        'OPTIONS': {
            'debug': DEBUG,
        },
    },
]
```

:tada:
