### ISSUE TITLE
no coverage for the templates

### ISSUE THREAD

**Issue by matrixise** [nedbat/django_coverage_plugin#43] opened 2017-04-06 07:46 UTC
Hi all,

I am using Python 3.5, django 1.9, coverage 4.3.4 and django-coverage-plugin (1.5.0)

Here is my `.coveragerc`

```
[run]
branch = True
omit =
    */migrations/*
plugins =
   django_coverage_plugin
```

but as you can check in the following report, the coverage of my templates is empty.

```
$ coverage report | grep html
internship/templates/internship_detail.html                         46     46      0      0     0%
internship/templates/internship_modification_student.html          112    112      0      0     0%
internship/templates/internships.html                              202    202      0      0     0%
internship/templates/internships_home.html                          83     83      0      0     0%
internship/templates/internships_masters.html                      137    137      0      0     0%
internship/templates/internships_stud.html                         235    235      0      0     0%
internship/templates/period_create.html                             49     49      0      0     0%
internship/templates/period_places_edit.html                        24     24      0      0     0%
internship/templates/periods.html                                   58     58      0      0     0%
```

Any idea ?

**Comment by PamelaM** [comment] 2017-04-06 12:12
Thanks for the report.

I'll look into this tonight(-ish). 

 If you've got the time, could you try with `django-coverage-plugin==1.4.2`, just to rule out something having changed in `1.5.0` such that the tests pass, but things fail anyway.

**Comment by matrixise** [comment] 2017-04-06 12:39
I have tried with django-coverage-plugin==1.4.2 but I have the same result.

Just added `django_coverage_plugin` in my .coveragerc file, I can see the list of my templates, but 0.00% percent for all of them.

Do you have an example ?

Thank you

**Comment by matrixise** [comment] 2017-04-06 19:57
@PamelaM I have checked with an other project and the plugin works fine but I don't know why it does not work with my main project. We can close, but maybe I will debug it in the future.

**Comment by PamelaM** [comment] 2017-04-07 00:42
I'd do a compare & contrast of the django settings - especially wrt settings.TEMPLATES entries have `'OPTIONS': {'debug': True}`

**Comment by PamelaM** [comment] 2017-04-07 12:49
Closing.  If you find the cause,  please follow up here.

**Closed** 2017-04-07 12:53 UTC
